# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Upload AAB to Google Play"
  lane :playstore do |options|
    upload_params = {
        aab: options[:aab],
        package_name: ENV['SUPPLY_PACKAGE_NAME'],
        json_key_data: ENV['PLAY_JSON_KEY'],
        track: options[:track] || 'internal',
        version_name: options[:version_name],
        version_code: options[:version_code],
        skip_upload_apk: true,
        skip_upload_screenshots: true,
        skip_upload_images: true,
        skip_upload_metadata: false,
        release_status: 'completed'
    }
    
    # Only add rollout if it has a valid value
    if options[:rollout] && !options[:rollout].to_s.empty?
      upload_params[:rollout] = options[:rollout]
    end
    
    upload_to_play_store(upload_params)
  end

  desc "Download Play-signed APK"
  lane :download_signed do
    supply(
        package_name: ENV['SUPPLY_PACKAGE_NAME'],
        json_key_data: ENV['PLAY_JSON_KEY'],
        track: 'internal',
        skip_upload_apk: true,
        skip_upload_aab: true,
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        download_apks: true
    )
  end
end
