name: Publish Store Contents to Google Play

on:
  workflow_dispatch:
    inputs:
      track:
        description: 'Track to publish to'
        required: true
        default: 'production'
        type: choice
        options:
          - internal
          - alpha
          - beta
          - production

jobs:
  publish-contents:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate track selection
        run: |
          echo "📦 Publishing store contents to track: ${{ inputs.track }}"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: false

      - name: Install Fastlane
        run: |
          gem install fastlane --no-document

      - name: Publish store metadata, images, and screenshots
        env:
          PLAY_JSON_KEY: ${{ secrets.PLAY_JSON_KEY }}
          SUPPLY_PACKAGE_NAME: com.vpnhood.connect.android
        run: |
          echo "🚀 Publishing store contents (metadata, images, screenshots) to track ${{ inputs.track }}"
          fastlane android publish_contents track:"${{ inputs.track }}"
          echo "✅ Store contents published successfully"
